[pytest]
addopts = -p no:cacheprovider --ignore=build-winx64 --ignore=build-winx64-test
markers =
    posix_only: test that runs only on POSIX platforms (Linux/macOS)
    windows_only: test that runs only on Windows platforms
