#!/bin/sh
set -eu

appdir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
export DLNA_SERVER_BIN="$appdir/usr/bin/dlna-server"
export DLNA_SERVER_GUI_DIR="$appdir/usr/share/dlna-server"

exec "$appdir/usr/bin/dlna-server-gui" "$@"
