#!/bin/sh
set -eu

appdir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
export DLNA_SERVER_BIN="$appdir/usr/bin/dlna-server"
export DLNA_SERVER_GUI_BIN="$appdir/usr/bin/dlna-server-gui-bin"
export PATH="$appdir/usr/bin:$PATH"

exec "$appdir/usr/bin/dlna-server-gui" "$@"
